solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/CreditCardControllerTest.kt

Escrever testes que cubram 100% das linhas da função `findCreditCard` do `CreditCardController`.

[KT4-01] Criar testes da função findCreditCard do CreditCardController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/CreditCardInvoiceControllerTest.kt

[KT4-04] Criar testes da função generateInvoice do CreditCardInvoiceController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/CreditCardInvoiceControllerTest.kt

Escrever testes que cubram 100% das linhas da função `getById` do `CreditCardInvoiceController`.

WIP[KT4-03] Testes do método getById da CreditCardInvoiceController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/controllers/CreditCardOperationControllerTest.kt

Escrever testes que cubram 100% das linhas da função `charge` do `CreditCardOperationController`.

[KT04-09] Teste do método charge

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/CreditCardOperationControllerTest.kt

[KT4-08] Criar testes da função getById do CreditCardOperationController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/domain/CreditCardServiceTest.kt

Escrever testes que cubram 100% das linhas da função `findCreditCardById` do `CreditCardService`.

[KT4-11] Criar testes da função findCreditCardById do CreditCardService

---

solutions/devsprint-luiz-zytkowski-4/src/test/transport/CreditCardInvoiceControllerTest.kt

Escrever testes que cubram 100% das linhas da função getByPeriod do CreditCardInvoiceController.

[KT4-06] Cria testes das funções do CreditCardInvoiceController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/CreditCardControllerTest.kt

[KT4-02] Criar testes da função requestCreditCard do CreditCardController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/domain/CreditCardOperationServiceTest.kt

Escrever testes que cubram 100% das linhas da função `getById` do `CreditCardOperationService`.

[KT4-13] Criar testes da função getById do CreditCardOperationService

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/domain/CreditCardInvoiceServiceTest.kt

[KT4-17] Cria testes da função getById do CreditCardInvoiceService

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/transport/CreditCardOperationControllerTest.kt

Escrever testes que cubram 100% das linhas da função `rollback` do `CreditCardOperationController`.

[KT4-37] Criar testes da função rollback do CreditCardOperationController

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/domain/CreditCardInvoiceServiceTest.kt

Escrever testes que cubram 100% das linhas da função `getByPeriod` do `CreditCardInvoiceService`.

[KT4-18] Criar testes da função getByPeriod do CreditCardInvoiceService

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/AccountManagementGatewayTest.kt

Escrever testes que cubram 100% das linhas da função `getByCPF` do `AccountManagementGateway`.

[KT4-21] Criar testes da função getByCPF do AccountManagementGateway

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/domain/CreditCardInvoiceServiceTest.kt

Escrever testes que cubram 100% das linhas da função `generateInvoice` do `CreditCardInvoiceService`.

[KT4-20] Criar testes da função generateInvoice do CreditCardInvoiceService

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/AccountManagementGatewayTest.kt

O segundo cenário retorna as mensagens esperadas, mas não passa no report.

[WIP] [KT4-22] Cria teste da função withdraw do AccountManagementGateway

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/domain/CreditCardOperationServiceTest.kt

Escreve testes que cobrem 100% das linhas da função rollback do CreditCardOperationService.

[KT4-15] Cria testes para função rollback do Service

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/AccountManagementGatewayTest.kt

Escrever testes que cubram 100% das linhas da função `getAccountById` do `AccountManagementGateway`.

[KT4-24] Criar testes da função getAccountById do AccountManagementGateway

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/CreditCardDAOTest.kt

Escrever testes que cubram 100% das linhas da função `getByTaxId` do `CreditCardDAO`.

[KT4-27] Criar testes da função getByTaxId do CreditCardDAO

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/AntiFraudGatewayTest.kt

Escrever testes que cubram 100% das linhas da função `creditCardEligibility` do `AntiFraudGateway`.

[KT4-25] Criar testes da função creditCardEligibility do AntiFraudGateway

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/CreditCardDAOTest.kt

Escreve testes que cobrem 100% das linhas da função create do CreditCardDAO

[KT4-28] Cria testes para função create do CreditCardDAO

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/CreditCardInvoiceDAOTest.kt

Escrever testes que cubram 100% das linhas da função `getInvoiceById` do `CreditCardInvoiceDAO`.

[KT4-30] Criar testes da função getInvoiceById do CreditCardInvoiceDAO

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/CreditCardDAOTest.kt

[KT4-29] Criar testes da função update do CreditCardDAO

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/CreditCardOperationDAOTest.kt

Escreve testes que cobrem 100% das linhas da função listByPeriod do CreditCardOperationDAO

[KT4-36] Cria testes da função listByPeriod do CreditCardOperationDAO

---

solutions/devsprint-luiz-zytkowski-4/src/test/io/devpass/creditcard/data/CreditCardInvoiceDAOTest.kt

Escrever testes que cubram 100% das linhas da função `update` do `CreditCardInvoiceDAO`.

[KT4-32] Criar testes da função update do CreditCardInvoiceDAO 
